#!/usr/bin/env python3
"""
Generate static data snapshot for GitHub Pages deployment.

Run from the project root:
    python generate_static_data.py

Outputs docs/static_data.js — commit both docs/index.html and
docs/static_data.js to publish an updated snapshot.
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Make sure we run from the project root so relative paths work
_ROOT = Path(__file__).parent.parent
os.chdir(_ROOT)
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from app import app  # noqa: E402 — must be after chdir

ENDPOINTS = [
    "/api/bracket",
    "/api/teams",
    "/api/tournament",
    "/api/groups",
    "/api/group_standings",
    "/api/bets",
    "/api/group_odds",
    "/api/validate",
    "/api/valuebets",
    "/api/team_stats",
]


def main():
    client = app.test_client()
    data: dict = {}
    errors: list[str] = []

    for endpoint in ENDPOINTS:
        print(f"  fetching {endpoint} …", end=" ", flush=True)
        try:
            resp = client.get(endpoint)
            if resp.status_code == 200:
                payload = resp.get_json()
                data[endpoint] = payload
                size = len(json.dumps(payload))
                print(f"OK  ({size:,} chars)")
            else:
                print(f"ERROR {resp.status_code}")
                errors.append(f"{endpoint}: HTTP {resp.status_code}")
                data[endpoint] = None
        except Exception as exc:
            print(f"EXCEPTION: {exc}")
            errors.append(f"{endpoint}: {exc}")
            data[endpoint] = None

    # Write output to both docs/ and static/
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    js = (
        f"// Auto-generated by generate_static_data.py\n"
        f"// Snapshot: {timestamp}\n"
        f"window.STATIC_DATA = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n"
    )

    for target_dir in [Path("docs"), Path("static")]:
        target_dir.mkdir(exist_ok=True)
        out_path = target_dir / "static_data.js"
        out_path.write_text(js, encoding="utf-8")
        size_kb = out_path.stat().st_size / 1024
        print(f"\nWrote {out_path}  ({size_kb:.1f} KB)")

        # Also inline the data into index.html
        import re as _re
        index_path = target_dir / "index.html"
        if index_path.exists():
            html = index_path.read_text(encoding="utf-8")
            data_line = f"window.STATIC_DATA = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};"
            pattern = r'(<script>)\n// Auto-generated by generate_static_data\.py\n// Snapshot: [^\n]+\nwindow\.STATIC_DATA = \{.*?\};\n(</script>)'
            replacement = f'<script>\n// Auto-generated by generate_static_data.py\n// Snapshot: {timestamp}\n{data_line}\n\\2'
            new_html, count = _re.subn(pattern, replacement, html, count=1, flags=_re.DOTALL)
            if count:
                index_path.write_text(new_html, encoding="utf-8")
                print(f"Updated {index_path}")
            else:
                # If no inline block found, we just rely on the static_data.js script tag
                print(f"Skipped inlining for {index_path} (no block found)")

    if errors:
        print("\nWarnings (some endpoints failed):")
        for e in errors:
            print(f"  • {e}")
    else:
        print("All endpoints OK — ready to deploy.")

    print("\nNext steps:")
    print("  git add docs/static_data.js docs/index.html")
    print("  git commit -m 'update static snapshot'")
    print("  git push")


if __name__ == "__main__":
    main()
